apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom
  template:
    metadata:
      labels:
        app: ecom
    spec:
      containers:
        - name: ecom
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
