version: '3.9'

services:
  app:
    image: eclipse-temurin:21-jdk
    container_name: ecom
    working_dir: /app
    volumes:
      - ./target/ecom-0.0.1-SNAPSHOT.jar:/app/ecom.jar
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ecom_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    command: ["java", "-jar", "ecom.jar"]
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecom_db
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
