# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Step 2: Set up Java (for Maven build)
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    
    # Step 3: Build the application with Maven
    # - name: Build with Maven
      # run: mvn clean package
    
    # Step 4: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Run docker-compose
      run: docker-compose up -d --build

    - name: Health check (replace with your logic)
      run: curl --fail http://localhost:8080 || exit 1

    - name: Shut down
      run: docker-compose down
